export type ServiceProvider = {
  id: string;
  name: string;
  category: string;
  rating: number;
  reviews: number;
  priceRange: '$' | '$$' | '$$$' | '$$$$';
  areas: string[];
  responseTime: string;
  image: string;
  description: string;
  phone: string;
  isAvailable: boolean;
  eta?: string;
};

export const MOCK_PROVIDERS: ServiceProvider[] = [
  // Landscaping
  {
    id: '1',
    name: 'Island Gardens',
    category: 'landscaping',
    rating: 4.8,
    reviews: 124,
    priceRange: '$$',
    areas: ['simpson-bay', 'maho', 'cupecoy', 'cole-bay'],
    responseTime: '15 min',
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=200&h=200&fit=crop',
    description: 'Professional landscaping services for villas and commercial properties. Lawn mowing, tree trimming, garden design.',
    phone: '+1-721-555-0101',
    isAvailable: true,
    eta: '20 min',
  },
  {
    id: '2',
    name: 'Tropical Trim',
    category: 'landscaping',
    rating: 4.6,
    reviews: 89,
    priceRange: '$',
    areas: ['philipsburg', 'cay-hill', 'south-reward'],
    responseTime: '30 min',
    image: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?w=200&h=200&fit=crop',
    description: 'Affordable lawn care and maintenance. Weekly or one-time services available.',
    phone: '+1-721-555-0102',
    isAvailable: true,
    eta: '45 min',
  },
  // Taxi
  {
    id: '3',
    name: 'SXM Rides',
    category: 'taxi',
    rating: 4.9,
    reviews: 342,
    priceRange: '$$',
    areas: ['philipsburg', 'simpson-bay', 'maho', 'marigot', 'grand-case'],
    responseTime: '5 min',
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=200&h=200&fit=crop',
    description: 'Reliable taxi service across St. Maarten. Airport transfers, island tours, and late-night rides.',
    phone: '+1-721-555-0103',
    isAvailable: true,
    eta: '5 min',
  },
  {
    id: '4',
    name: 'Island Cruisers',
    category: 'taxi',
    rating: 4.7,
    reviews: 156,
    priceRange: '$$$',
    areas: ['simpson-bay', 'maho', 'cupecoy', 'orient-bay'],
    responseTime: '10 min',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=200&h=200&fit=crop',
    description: 'Luxury vehicle service with professional drivers. Perfect for airport pickups and special occasions.',
    phone: '+1-721-555-0104',
    isAvailable: true,
    eta: '12 min',
  },
  // Babysitting
  {
    id: '5',
    name: 'Caring Hands',
    category: 'babysitting',
    rating: 5.0,
    reviews: 67,
    priceRange: '$$',
    areas: ['simpson-bay', 'cupecoy', 'cole-bay', 'marigot'],
    responseTime: '20 min',
    image: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?w=200&h=200&fit=crop',
    description: 'Experienced and certified childcare providers. CPR certified, background checked.',
    phone: '+1-721-555-0105',
    isAvailable: true,
    eta: '30 min',
  },
  {
    id: '6',
    name: 'Island Nannies',
    category: 'babysitting',
    rating: 4.8,
    reviews: 92,
    priceRange: '$$$',
    areas: ['maho', 'orient-bay', 'grand-case', 'cul-de-sac'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=200&h=200&fit=crop',
    description: 'Professional nanny services for tourists and residents. Multilingual staff available.',
    phone: '+1-721-555-0106',
    isAvailable: false,
    eta: '2 hours',
  },
  // Food Delivery
  {
    id: '7',
    name: 'SXM Eats Express',
    category: 'food-delivery',
    rating: 4.5,
    reviews: 523,
    priceRange: '$',
    areas: ['philipsburg', 'simpson-bay', 'maho', 'marigot'],
    responseTime: '45 min',
    image: 'https://images.unsplash.com/photo-1526367790999-015075668a5a?w=200&h=200&fit=crop',
    description: 'Fast food delivery from your favorite local restaurants. Real-time tracking.',
    phone: '+1-721-555-0107',
    isAvailable: true,
    eta: '35 min',
  },
  {
    id: '8',
    name: 'Gourmet Go',
    category: 'food-delivery',
    rating: 4.7,
    reviews: 198,
    priceRange: '$$',
    areas: ['cupecoy', 'cole-bay', 'grand-case', 'orient-bay'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200&h=200&fit=crop',
    description: 'Premium delivery from fine dining restaurants. Temperature-controlled transport.',
    phone: '+1-721-555-0108',
    isAvailable: true,
    eta: '55 min',
  },
  // Home Repair
  {
    id: '9',
    name: 'Fix-It Felix',
    category: 'home-repair',
    rating: 4.6,
    reviews: 145,
    priceRange: '$$',
    areas: ['simpson-bay', 'cole-bay', 'south-reward', 'cay-hill'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=200&h=200&fit=crop',
    description: 'All-around handyman services. Plumbing, electrical, carpentry, and general repairs.',
    phone: '+1-721-555-0109',
    isAvailable: true,
    eta: '1 hour',
  },
  {
    id: '10',
    name: 'SXM Plumbers',
    category: 'home-repair',
    rating: 4.9,
    reviews: 203,
    priceRange: '$$$',
    areas: ['philipsburg', 'marigot', 'french-quarter', 'cay-hill'],
    responseTime: '30 min',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=200&h=200&fit=crop',
    description: 'Licensed plumbing professionals. Emergency services available 24/7.',
    phone: '+1-721-555-0110',
    isAvailable: true,
    eta: '25 min',
  },
  // Cleaning
  {
    id: '11',
    name: 'Sparkle Squad',
    category: 'cleaning',
    rating: 4.8,
    reviews: 178,
    priceRange: '$$',
    areas: ['maho', 'cupecoy', 'orient-bay', 'cul-de-sac'],
    responseTime: '2 hours',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=200&h=200&fit=crop',
    description: 'Professional cleaning for homes and vacation rentals. Deep cleaning available.',
    phone: '+1-721-555-0111',
    isAvailable: true,
    eta: '3 hours',
  },
  {
    id: '12',
    name: 'Fresh Start',
    category: 'cleaning',
    rating: 4.5,
    reviews: 134,
    priceRange: '$',
    areas: ['simpson-bay', 'cole-bay', 'grand-case'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=200&h=200&fit=crop',
    description: 'Affordable cleaning services. Regular maintenance or one-time deep cleans.',
    phone: '+1-721-555-0112',
    isAvailable: true,
    eta: '1.5 hours',
  },
  // Pet Care
  {
    id: '13',
    name: 'Paws & Relax',
    category: 'pet-care',
    rating: 5.0,
    reviews: 87,
    priceRange: '$$',
    areas: ['simpson-bay', 'maho', 'marigot', 'french-quarter'],
    responseTime: '30 min',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=200&h=200&fit=crop',
    description: 'Dog walking, pet sitting, and basic grooming. Insured and pet-first-aid certified.',
    phone: '+1-721-555-0113',
    isAvailable: true,
    eta: '40 min',
  },
  // Moving
  {
    id: '14',
    name: 'Island Movers',
    category: 'moving',
    rating: 4.7,
    reviews: 112,
    priceRange: '$$$',
    areas: ['philipsburg', 'simpson-bay', 'cole-bay', 'marigot'],
    responseTime: '2 hours',
    image: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=200&h=200&fit=crop',
    description: 'Professional moving services. Trucks, packing supplies, and careful handling.',
    phone: '+1-721-555-0114',
    isAvailable: false,
    eta: '4 hours',
  },
  // Construction
  {
    id: '15',
    name: 'Build Right SXM',
    category: 'construction',
    rating: 4.8,
    reviews: 76,
    priceRange: '$$$$',
    areas: ['cupecoy', 'cole-bay', 'orient-bay', 'cul-de-sac'],
    responseTime: '1 day',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop',
    description: 'Licensed construction and renovation. Painting, tiling, and major renovations.',
    phone: '+1-721-555-0115',
    isAvailable: true,
    eta: 'Tomorrow',
  },
  // Property Care
  {
    id: '16',
    name: 'Villa Care Pro',
    category: 'property',
    rating: 4.9,
    reviews: 94,
    priceRange: '$$$',
    areas: ['maho', 'simpson-bay', 'orient-bay', 'grand-case'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=200&h=200&fit=crop',
    description: 'Complete property management. Pool maintenance, housekeeping, and guest services.',
    phone: '+1-721-555-0116',
    isAvailable: true,
    eta: '45 min',
  },
  // Car Rental
  {
    id: '17',
    name: 'Island Wheels',
    category: 'car-rental',
    rating: 4.7,
    reviews: 186,
    priceRange: '$',
    areas: ['simpson-bay', 'maho', 'philipsburg', 'marigot'],
    responseTime: '30 min',
    image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=200&h=200&fit=crop',
    description: 'Wide selection of vehicles from compact cars to SUVs. Airport pickup and drop-off available.',
    phone: '+1-721-555-0117',
    isAvailable: true,
    eta: '30 min',
  },
  {
    id: '18',
    name: 'SXM Auto Rentals',
    category: 'car-rental',
    rating: 4.5,
    reviews: 134,
    priceRange: '$',
    areas: ['cole-bay', 'cay-hill', 'south-reward', 'french-quarter'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=200&h=200&fit=crop',
    description: 'Affordable daily and weekly rentals. Free delivery to your hotel or villa.',
    phone: '+1-721-555-0118',
    isAvailable: true,
    eta: '1 hour',
  },
  // Mechanic
  {
    id: '19',
    name: 'SXM Auto Care',
    category: 'mechanic',
    rating: 4.9,
    reviews: 211,
    priceRange: '$',
    areas: ['cole-bay', 'simpson-bay', 'philipsburg', 'cay-hill'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=200&h=200&fit=crop',
    description: 'Full-service auto repair shop. Engine diagnostics, brake service, AC repair, and more.',
    phone: '+1-721-555-0119',
    isAvailable: true,
    eta: '1 hour',
  },
  {
    id: '20',
    name: 'Quick Fix Garage',
    category: 'mechanic',
    rating: 4.6,
    reviews: 98,
    priceRange: '$$',
    areas: ['marigot', 'grand-case', 'french-quarter', 'cul-de-sac'],
    responseTime: '2 hours',
    image: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=200&h=200&fit=crop',
    description: 'Mobile mechanic service. We come to you for oil changes, tire repairs, and roadside assistance.',
    phone: '+1-721-555-0120',
    isAvailable: true,
    eta: '2 hours',
  },
  // Tutoring
  {
    id: '21',
    name: 'SXM Scholars',
    category: 'tutoring',
    rating: 4.9,
    reviews: 145,
    priceRange: '$',
    areas: ['philipsburg', 'simpson-bay', 'cole-bay', 'cay-hill'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=200&h=200&fit=crop',
    description: 'Certified tutors for all ages. Math, English, Science, SAT/ACT prep, and homework help.',
    phone: '+1-721-555-0121',
    isAvailable: true,
    eta: '1 hour',
  },
  {
    id: '22',
    name: 'Island Tutors',
    category: 'tutoring',
    rating: 4.7,
    reviews: 89,
    priceRange: '$$',
    areas: ['marigot', 'grand-case', 'orient-bay', 'french-quarter'],
    responseTime: '2 hours',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&h=200&fit=crop',
    description: 'Bilingual tutoring in French and English. Primary school through university level subjects.',
    phone: '+1-721-555-0122',
    isAvailable: true,
    eta: '2 hours',
  },
  // Hair Care
  {
    id: '23',
    name: 'Island Glam Studio',
    category: 'haircare',
    rating: 4.8,
    reviews: 234,
    priceRange: '$',
    areas: ['simpson-bay', 'maho', 'cupecoy', 'cole-bay'],
    responseTime: '30 min',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=200&h=200&fit=crop',
    description: 'Full-service hair salon. Cuts, color, braids, extensions, and special occasion styling.',
    phone: '+1-721-555-0123',
    isAvailable: true,
    eta: '45 min',
  },
  {
    id: '24',
    name: 'Fresh Cuts SXM',
    category: 'haircare',
    rating: 4.6,
    reviews: 178,
    priceRange: '$',
    areas: ['philipsburg', 'cay-hill', 'south-reward', 'marigot'],
    responseTime: '15 min',
    image: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=200&h=200&fit=crop',
    description: 'Modern barbershop and hair care. Fades, lineups, beard trims, and hair treatments.',
    phone: '+1-721-555-0124',
    isAvailable: true,
    eta: '20 min',
  },
  // Pool Service
  {
    id: '25',
    name: 'Crystal Clear Pools',
    category: 'pool-service',
    rating: 4.9,
    reviews: 112,
    priceRange: '$',
    areas: ['maho', 'cupecoy', 'simpson-bay', 'orient-bay'],
    responseTime: '1 hour',
    image: 'https://images.unsplash.com/photo-1572331165267-854da2b021b1?w=200&h=200&fit=crop',
    description: 'Professional pool cleaning and maintenance. Chemical balancing, filter cleaning, and equipment repair.',
    phone: '+1-721-555-0125',
    isAvailable: true,
    eta: '1 hour',
  },
  {
    id: '26',
    name: 'AquaPro SXM',
    category: 'pool-service',
    rating: 4.7,
    reviews: 76,
    priceRange: '$$',
    areas: ['cole-bay', 'cay-hill', 'grand-case', 'cul-de-sac'],
    responseTime: '2 hours',
    image: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=200&h=200&fit=crop',
    description: 'Complete pool services for villas and resorts. Weekly maintenance plans and emergency repairs available.',
    phone: '+1-721-555-0126',
    isAvailable: true,
    eta: '2 hours',
  },
];

export const getProvidersByCategory = (categoryId: string): ServiceProvider[] => {
  return MOCK_PROVIDERS.filter(p => p.category === categoryId);
};

export const getProvidersByArea = (areaId: string): ServiceProvider[] => {
  return MOCK_PROVIDERS.filter(p => p.areas.includes(areaId));
};
